version: '3.5'

services:
#  postgres:
#    container_name: postgres-crud
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: super_admin
#      POSTGRES_PASSWORD: SomeSecretPassword
#      PGDATA: /data/postgres
#    volumes:
#      - ./postgres-data:/data/postgres
#      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
#    ports:
#      - "5432:5432"
  mongodb:
    image: mongo:6.0.6
    environment:
      MONGO_INITDB_DATABASE: restaurant_app
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017-27019:27017-27019"
#  webapp:
#    container_name: webapp-crud
#    image: matesz-teaching/docker-java-crud:latest
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/restaurant_app
#    depends_on:
#      - mongodb
#      - postgres
